version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    # - ACCESS_KEY=${ACCESS_KEY}
    # - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - rabbitmq
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

networks:
  my_network:
